###########################################################
#                  SIGNER CONFIG                          #
#                                                         #
###########################################################
[settings]

# settings you might need to change:
# your individual address
KEY = "osmo1cs4jxnxjl54y3xnk4aud5g4n334nxsnnxaqegn"
# a good node. if empty, forces offline mode
RPC = ""
# account number, for offline siging. if empty a good rpc is required
ACCOUNT = "177061"

#### less likely youll need to change these ####
# multisig address
MULTISIG = "osmo1apm6afyajnplmj5pn0x5us7wrxhfhge4590fdv"
# where the txs are located. if empty, forces offline mode
REPO = ""
# should probably only change this if using ledger
KEYRING = "os"
# chain-id
CHAIN = "osmosis-1"
